[versions]
appcompat = "1.6.1"
constraintlayout = "2.1.4"
espressoCore = "3.5.1"
gson = "2.10.1"
junit = "4.13.2"
junitVersion = "1.1.5"
material = "1.9.0"
shizuku = "13.1.4"
hiddenapibypass = "4.3"

[libraries]
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "junitVersion" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
junit = { module = "junit:junit", version.ref = "junit" }
material = { module = "com.google.android.material:material", version.ref = "material" }
shizukuApi = { module = "dev.rikka.shizuku:api", version.ref = "shizuku" }
hiddenapibypass = { module = "org.lsposed.hiddenapibypass:hiddenapibypass", version.ref = "hiddenapibypass" }
shizukuProvider = { module = "dev.rikka.shizuku:provider", version.ref = "shizuku" }